repository: yangby-cryptape/yangby-cryptape.github.io
remote_theme: yangby-cryptape/yangby-cryptape.github.io@theme
title: Fish Out Of Water
description: Bite Off More Than I Can Chew
author:
  name: Boyu Yang
  url: /about#contact
google_analytics:
mathjax:
  url:
    js: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js
asciinema_player:
  url:
    css: https://cdn.jsdelivr.net/npm/asciinema-player@2.6.1/resources/public/css/asciinema-player.min.css
    js: https://cdn.jsdelivr.net/npm/asciinema-player@2.6.1/resources/public/js/asciinema-player.min.js
